// Generated by CoffeeScript 1.6.3
console.log('test for google drive based on enterprise framework...');

casper.options.logLevel = 'info';

casper.test.begin('Casper Test for enterprise', 4, function(test) {
  casper.start("http://nimbusbase.github.io/enterprise/", function() {
    test.assertExists('#google_login', "login button located");
    return this.mouse.click('#google_login');
  });
  casper.then(function() {
    var login_form, title;
    title = this.getTitle();
    console.log(title);
    if (title === 'enterprise framework') {
      return;
    }
    login_form = test.assertExists('form#gaia_loginform');
    if ((title === '登录 - Google 帐户' || 'Sign in - Google Accounts') && login_form) {
      this.fill('form#gaia_loginform', {
        Email: 'release@nimbusbase.com',
        Passwd: 'freethecloud2013'
      }, true);
      return console.log('Filled in with test account and submitted');
    }
  });
  casper.then(function() {
    var title;
    title = this.getTitle();
    if (title === "Request for Permission") {
      this.mouse.click('#submit_approve_access');
      return console.log('Granted permission');
    }
  });
  casper.then(function() {
    this.evaluateOrDie(function() {
      console.log();
      return Nimbus.Auth.authorized();
    }, 'Login Failed');
    return test.done();
  });
  casper.run();
});
